name: Build and deploy app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      DISABLE_ESLINT_PLUGIN: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.17.x'

      - name: Install NPM packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create 404.html
        run: cp ./build/index.html ./build/404.html

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: production-build
          path: ./build
          
  units:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.17.x'

      - name: Install NPM packages
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --passWithNoTests

  deploy:
    name: Deploy on Github Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v2.1.0
       with:
         name: production-build
         path: ./build
    
     - name: GitHub Pages
       uses: peaceiris/actions-gh-pages@v3.7.3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./build

